### ISSUE TITLE
Any plans to upgrade to omnipay 3?

### ISSUE THREAD

**Issue by gavinjackson** [delatbabel/omnipay-fatzebra#2]
Hello, I'm looking at using this library - just checking to see if there were plans to upgrade this module to omnipay 3 (or you would be interested in a PR)?

**Comment by delatbabel** [comment]
Hi Gavin,

A couple of years ago I became seriously ill for an extended period and had to drop out of maintaining most of my repositories on github.  I'm slowly getting back once again but I have a huge backlog of stuff to even read through let alone maintain.  I would be happy to take a PR or cede ownership to someone with more spoons than me to maintain this.

**Comment by gavinjackson** [comment]
Hi Del,

Sorry to hear about your illness mate (good to hear you are back in action!), thanks for getting back to me, I'll be in touch with a PR if we go forward!

Cheers,
Gav
